/**
 * @typedef {{
 *   id: number,
 *   nome: string,
 *   loja: string,
 *   descricao: string,
 *   preco: number,
 *   estoque?: number,
 *   images: string[],
 *   categoria: string,
 *   tags: string[],
 * }} Produto
 */

/** @type {Produto[]} */
export const PRODUTOS = [
  {
    id: 1,
    nome: "Liquidificador Turbo 900W",
    images: [
      "https://m.media-amazon.com/images/I/714xUeXxkHL._UF894,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/51s1-Aw1vjL.jpg",
      "https://storage-v2-dev.s3.amazonaws.com/01369b31-3cf0-42b1-b832-7a10c6e39c312025-07-15T12%3A20%3A21.284Z.webp",
      "https://m.media-amazon.com/images/I/71yYWEvvFnL._UF894,1000_QL80_.jpg",
    ],
    preco: 249.9,
    estoque: 12,
    loja: "Mundo Eletro",
    descricao: `Com potência de 900W e 12 velocidades, o Liquidificador Turbo é ideal para preparar vitaminas cremosas, sopas e massas leves, trazendo praticidade e rapidez para o dia a dia com um copo resistente de 2 litros.`,
    categoria: "Eletrodomésticos",
    tags: ["casa", "cozinha", "bebidas"],
  },
  {
    id: 2,
    nome: "Smartphone Galaxy X12",
    images: [
      "https://www.pcinformatica.info/images/produto/img_51.0770_foto_1.jpg",
      "https://a-static.mlcdn.com.br/800x560/smartphone-samsung-galaxy-a12-64gb-azul-4gb-ram-65-cam-quadrupla-selfie-8mp-dual-chip/magazineluiza/155616000/63913a498f8efd9dea8904c4dd38b467.jpg",
      "https://d3bkgvrq5dqryp.cloudfront.net/Custom/Content/Products/21/68/21687_product-00080235_m9_637735344537155163.webp",
      "https://gazin-images.gazin.com.br/40pHG2U6WbXF1J6MOse5yCnUeUg=/1920x/filters:format(webp):quality(75)/https://gazin-marketplace.s3.amazonaws.com/midias/imagens/2020/12/smartphone-samsung-galaxy-a-12-65-octa-core-64gb-4gb-camera-quadrupla-112012511807.jpg",
      "https://mtec.com.vc/wp-content/uploads/2024/03/Tablet_Samsung_Tab_a9-removebg-preview.png",
    ],
    preco: 1999.0,
    estoque: 7,
    loja: "TechWorld",
    descricao: `O Galaxy X12 combina desempenho ágil com tela AMOLED de 6,5'', câmera tripla e 128GB de armazenamento, oferecendo qualidade para fotos, vídeos e jogos, além de bateria de longa duração com carregamento rápido.`,
    categoria: "Eletrônicos",
    tags: ["tecnologia", "celular", "mobile"],
  },
  {
    id: 3,
    nome: "Tênis Esportivo AirFlex",
    images: [
      "https://lovedema.com/cdn/shop/files/9_25311406089840.jpg?v=1700073428",
      "https://lovedema.com/cdn/shop/files/224816472733.jpg?v=1700073428",
      "https://lovedema.com/cdn/shop/files/4579292900338.jpg?v=1700073428",
      "https://femory.com.br/cdn/shop/files/tenis-esportivo-unissex-super-macio-leve-e-respiravel-airflex-pro_branco_FEMORY_640x.webp?v=1741214940",
      "https://lovedema.com/cdn/shop/files/1618188399922.webp?v=1700073428",
    ],
    preco: 349.9,
    estoque: 25,
    loja: "Fit&Run",
    descricao: `O Tênis Esportivo AirFlex é leve, respirável e moderno, proporcionando conforto durante corridas e treinos, com palmilha anatômica, amortecimento eficiente e sola antiderrapante para segurança em diversos pisos.`,
    categoria: "Moda",
    tags: ["esporte", "calçado", "fitness"],
  },
  {
    id: 4,
    nome: "Cafeteira Expresso Automática",
    images: [
      "https://www.cafefacil.com.br/media/product/eea/cafeteira-expresso-automatica-orion-espressione-620t-220v-dbb.jpg",
      "https://maquinasecafe.com.br/media/catalog/product/E/C/ECAM-23210B-127V_02-5585da3c.webp",
      "https://walitastore.vtexassets.com/arquivos/ids/160944/EP1220_1_Cafeteira-Espresso-Automatica-Serie-1200-Philips-Walita-Preta_Frente_2.png?v=638799121578100000",
      "https://images.tcdn.com.br/img/img_prod/937261/gaggia_anima_prestige_cafeteira_expresso_automatica_429_1_dce01b2bb3f77c99fd2d246b0ced7c46.jpg",
      "https://cdn.leroymerlin.com.br/products/cafeteira_expresso_gaggia_maquina_automatica_syncrony_logic_c_1567019551_0c18_600x600.jpg",
    ],
    preco: 899.0,
    estoque: 5,
    loja: "Utilitários CasaFácil",
    descricao: `A Cafeteira Expresso Automática prepara cafés encorpados com moagem integrada, vaporizador para espumas cremosas e funções programáveis, garantindo praticidade para amantes de café em casa.`,
    categoria: "Eletrodomésticos",
    tags: ["café", "cozinha", "casa"],
  },
  {
    id: 5,
    nome: "Fone de Ouvido Bluetooth Pro",
    images: [
      "https://i.zst.com.br/thumbs/12/1e/11/954089697.jpg",
      "https://m.media-amazon.com/images/I/614uX-4VGLL._UF1000,1000_QL80_.jpg",
      "https://cdn.awsli.com.br/600x450/906/906133/produto/259213411/foe-air-pro-3-uga0w3sloa.jpeg",
      "https://a-static.mlcdn.com.br/800x560/fone-bluetooth-air-pro-tws-3-compativel-com-airp-pro-3-airs/folkseletronicosltda/fonetws/cd4625bf78b5f5352fe5ed5790809651.jpeg",
      "https://cdn.sistemawbuy.com.br/arquivos/b0c36266e1a9271e949cf113bd58d369/produtos/64172de58168f/a-64172de5ae776.jpg",
    ],
    preco: 599.0,
    estoque: 15,
    loja: "Mobile Center",
    descricao: `Os Fones Bluetooth Pro oferecem cancelamento de ruído ativo, som de alta qualidade e bateria duradoura, ideais para trabalho, viagens e lazer, com design confortável e conexão estável.`,
    categoria: "Eletrônicos",
    tags: ["áudio", "musica", "wireless"],
  },
  {
    id: 6,
    nome: "Mochila Impermeável Urban",
    images: [
      "http://lojaviego.com.br/cdn/shop/files/MochilaImpermeavelMasculinaBlackUrban_7__7.webp?v=1713739220",
      "https://mrcatstore.vteximg.com.br/arquivos/ids/414365-1000-1200/MOCHILA-NYLON-URBAN---PRETO-01.jpg?v=638621000362830000",
      "https://images.tcdn.com.br/img/img_prod/1148372/mochila_escolar_militar_de_trilha_impermeavel_urban_brasil_5_bolsos_velcro_exercito_wincy_3045_1_601bfbb069f67a8d3aa70000e9bdcf31.jpg",
      "https://lojaviego.com.br/cdn/shop/files/MochilaImpermeavelMasculinaBlackUrban_1__6_1340x.webp?v=1713739220",
      "http://teuspulos.com.br/cdn/shop/files/S74d38d08a65d4c9d964b8743778111adc.webp?v=1728533705",
    ],
    preco: 199.9,
    estoque: 30,
    loja: "UrbanStyle",
    descricao: `A Mochila Impermeável Urban é resistente, possui compartimento acolchoado para notebook e design moderno, perfeita para o dia a dia, viagens ou trabalho, mantendo seus pertences protegidos.`,
    categoria: "Moda",
    tags: ["acessórios", "viagem", "trabalho"],
  },
  {
    id: 7,
    nome: "Smart TV 55'' 4K Ultra HD",
    images: [
      "https://cdn.shoppub.io/cdn-cgi/image/w=600,h=600,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/aznhspsg/file.png",
      "https://lojaibyte.vteximg.com.br/arquivos/ids/433377-540-540/smart-tv-lg-55-2024-55UT8050PSA-alexa-wi-fi-bluetooth-01-min.jpg?v=638639865059230000",
      "https://fujiokadistribuidor.vteximg.com.br/arquivos/ids/210446",
      "https://m.media-amazon.com/images/I/61bnVBHdXGL._UF1000,1000_QL80_.jpg",
      "https://a-static.mlcdn.com.br/1500x1500/smart-tv-55-uhd-4k-led-samsung-55cu7700-wi-fi-bluetooth-alexa-3-hdmi/magazineluiza/237016200/f98b4c5561389e57142b0978489f2456.jpg",
    ],
    preco: 2799.0,
    estoque: 8,
    loja: "MegaEletrônicos",
    descricao: `A Smart TV 55'' 4K Ultra HD oferece imagens nítidas com suporte a HDR, sistema Android integrado para apps e streaming, além de conectividade Wi-Fi e Bluetooth, transformando a sala em um verdadeiro cinema.`,
    categoria: "Eletrônicos",
    tags: ["tv", "home", "cinema"],
  },
  {
    id: 8,
    nome: "Bicicleta Speed Pro",
    images: [
      "https://static.santosbikes.com.br/public/santosbikes/imagens/produtos/5ed8e3958b2d0587ebce628c5fd35f4e.png",
      "https://lasmagrelas.com.br/wp-content/uploads/2021/11/IMG_3769.png",
      "https://images.tcdn.com.br/img/img_prod/394779/bicicleta_speed_gts_cambio_gts_14_marchas_gts_m1_speed_pro_1139_1_20250701154702.jpg",
      "https://images.tcdn.com.br/img/img_prod/359445/bicicleta_speed_reaod_swift_carbon_racevox_pro_disc_2025_369_1_3d80d03d7bd8c7f23f8c1fd80960fe7c.jpg",
      "https://static.santosbikes.com.br/public/santosbikes/imagens/produtos/000cf7312c92d738be6a7f4213b87575.png",
    ],
    preco: 3599.0,
    estoque: 3,
    loja: "Fit&Run",
    descricao: `A Bicicleta Speed Pro é construída em alumínio leve, com 21 marchas e design aerodinâmico, ideal para treinos intensos e competições, oferecendo desempenho, resistência e velocidade.`,
    categoria: "Esporte",
    tags: ["bike", "corrida", "fitness"],
  },
  {
    id: 9,
    nome: "Cadeira Gamer ErgoX",
    images: [
      "https://images.tcdn.com.br/img/img_prod/1231797/cadeira_gamer_g_hox_ch_8701_branco_azul_3274_1_d32cb9763eeecbd18a4a981ad321dcc3.jpg",
      "https://www.comfy.com.br/media/Sem_T_tulo-1.webp",
      "https://images.kabum.com.br/produtos/fotos/878082/cadeira-gamer-elg-syrax-ate-120-kg-apoio-lombar-cervical-e-ajuste-de-altura-preto-e-azul-ch36bkbl_1751045218_original.jpg",
      "https://a-static.mlcdn.com.br/800x560/cadeira-gamer-profissional-eaglex-s1-ajustavel-vermelho/cadeirasinc/fix7129vm/45ca36ee3d8de5af244ad922d8ab8205.jpeg",
      "https://a-static.mlcdn.com.br/800x560/cadeira-gamer-mymax-mx5-ate-150kg-com-almofadas-reclinavel-descanso-de-braco-2d-preto-mgch-mx5-bk/kabum/471630/82b0eb099a47bacaa1695245a24ee1d7.jpeg",
    ],
    preco: 1299.9,
    estoque: 10,
    loja: "OfficePlus",
    descricao: `A Cadeira Gamer ErgoX une ergonomia e conforto, com ajuste de altura, apoio lombar e design moderno, sendo perfeita para longas sessões de jogos ou trabalho no escritório.`,
    categoria: "Móveis",
    tags: ["conforto", "escritorio", "game"],
  },
  {
    id: 10,
    nome: "Relógio Inteligente FitBand 2",
    images: [
      "https://i.zst.com.br/thumbs/12/34/3a/1281648228.jpg",
      "https://assets.mlcdn.com.br/conteudoproduto/22/226960900/images/img-samsung__a.png",
      "https://ultraeletronicos.com/media/catalog/product/cache/1/image/650x/040ec09b1e35df139433887a97daa66f/m/i/miband2_cores_ot.jpg",
      "https://escolhasegura.com.br/wp-content/uploads/2021/02/Smartband-Samsung-Galaxy-Fit-2-Batimento-Cardiaco.jpg",
      "https://escolhasegura.com.br/wp-content/uploads/2021/02/Smartband-Samsung-Galaxy-Fit-2.jpg",
    ],
    preco: 499.0,
    estoque: 0,
    loja: "TechWorld",
    descricao: `O Relógio FitBand 2 monitora frequência cardíaca, passos e sono, além de contar com GPS integrado e notificações, sendo um aliado para saúde, esportes e organização diária.`,
    categoria: "Eletrônicos",
    tags: ["fitness", "wearable", "saúde"],
  },
  {
    id: 11,
    nome: "Forno Elétrico 45L",
    images: [
      "https://m.media-amazon.com/images/I/61J79Zm8NQL._UF894,1000_QL80_.jpg",
      "https://images.tcdn.com.br/img/img_prod/1029092/forno_eletrico_45l_c_timer_1750w_du_chef_plus_110v_3289920_1_8007b61d98a1bd93b1136c6de78cb6dc.jpg",
      "https://jcsbrasil.vteximg.com.br/arquivos/ids/190225-1000-1000/OFOR455-06.jpg?v=638865463985030000",
      "https://i.zst.com.br/thumbs/12/1d/13/155861270.jpg",
      "https://a-static.mlcdn.com.br/800x560/forno-eletrico-oster-45l-por-conveccao-1600w-ofor455-127v-pt/razakcomercial/forno-oster-ofor455-127v/a61645ab6f77dd111320e224adfa547c.jpeg",
    ],
    preco: 749.9,
    estoque: 6,
    loja: "Casa&Cozinha",
    descricao: `O Forno Elétrico 45L possui grill, múltiplas funções e timer digital, permitindo assar, gratinar e aquecer alimentos com praticidade e eficiência, ideal para cozinhas modernas.`,
    categoria: "Eletrodomésticos",
    tags: ["cozinha", "casa", "assados"],
  },
  {
    id: 12,
    nome: "Camisa Polo Premium",
    images: [
      "https://cdn.awsli.com.br/600x1000/2707/2707919/produto/304367449/c-lio-junior---cadastros--34--9j9ygmjln9.png",
      "https://images.tcdn.com.br/img/img_prod/826022/camisa_polo_premium_masculino_vinho_1200042485_p_gg_4973_1_5f1142ef42e79b72a3c728608e14d5c9.jpeg",
      "https://acdn-us.mitiendanube.com/stores/952/416/products/polo-premium-31-e74149e387a656dfdf16927252669105-1024-1024.png",
      "https://images.tcdn.com.br/img/img_prod/738950/camisa_polo_premium_baumgarten_slim_listrada_azul_nautico_2135_1_eeb2dea53def4538671b8e40d5ea0406.jpg",
      "https://fiezzo.com/cdn/shop/files/S313535923a2d4830960ff147cef4f6b8G_790x.webp?v=1695952579",
    ],
    preco: 129.9,
    estoque: 40,
    loja: "FashionStore",
    descricao: `A Camisa Polo Premium é confeccionada em algodão penteado de alta qualidade, oferecendo conforto, durabilidade e estilo, ideal para ocasiões casuais e profissionais.`,
    categoria: "Moda",
    tags: ["roupa", "casual", "masculino"],
  },
  {
    id: 13,
    nome: "Aspirador de Pó Vertical",
    images: [
      "https://assets.mlcdn.com.br/conteudoproduto/22/224264300/img/s-1-image.png",
      "https://m.media-amazon.com/images/I/71-pVjx4hCL.jpg",
      "https://images.tcdn.com.br/img/img_prod/1153568/aspirador_de_po_vertical_agratto_resid_2_em_1_duo_220v_1000w_nac_1309_1_54db572f018284aedb1a627583e0049c.jpg",
      "https://images.tcdn.com.br/img/img_prod/438510/aspirador_de_po_vertical_portatil_vassoura_eletrica_1000w_worker_11103_2_51ba92a25187d9c8c023eb8c76db2a7c.jpg",
      "https://io.convertiez.com.br/m/lojasedmil/shop/products/images/1274/medium/aspirador-de-po-electrolux-power-speed-stk12-vertical-e-portatil_8610.jpg",
    ],
    preco: 599.0,
    estoque: 9,
    loja: "Utilitários CasaFácil",
    descricao: `O Aspirador de Pó Vertical sem fio é leve, prático e eficiente, com bateria de longa duração, ideal para limpezas rápidas no dia a dia sem comprometer a potência de sucção.`,
    categoria: "Eletrodomésticos",
    tags: ["casa", "limpeza", "praticidade"],
  },
  {
    id: 14,
    nome: "Notebook UltraBook Z15",
    images: [
      "https://a-static.mlcdn.com.br/800x560/notebook-asus-vivobook-15-x1504za-intel-core-i5-1235u-8gb-ram-256gb-ssd-windows-11-tela-156-fhd-silver-nj985w/asus/90nb1022-m01el0/864f8e0e1ccb342ac601442603771387.jpeg",
      "https://www.notebookcheck.net/uploads/tx_nbc2/Z15_144.jpg",
      "https://www.tradework.com.br/media/catalog/product/cache/cd63a08b966d107aaaf66bd74393e948/M/5/M5-481PT-6851_acer.jpg",
      "https://i.zst.com.br/thumbs/12/17/1a/857945649.jpg",
    ],
    preco: 4299.0,
    estoque: 4,
    loja: "Mobile Center",
    descricao: `O Notebook UltraBook Z15 traz design fino e leve, com processador i7, SSD de 512GB e tela de alta resolução, perfeito para produtividade, estudos e trabalho criativo.`,
    categoria: "Eletrônicos",
    tags: ["computador", "trabalho", "tecnologia"],
  },
  {
    id: 15,
    nome: "Jaqueta Corta-Vento",
    images: [
      "https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/ihops/media/uploads/produtos/foto/bnhioajr/invicta-cortavento00180.jpg",
      "https://images.tcdn.com.br/img/img_prod/1182338/jaqueta_corta_vento_feminina_rosa_05_1245_1_5fd47e6e0616cfbb752beb1cca26fce9.jpg",
      "https://adaptive-images.uooucdn.com.br/tr:w-1100,h-1594,c-at_max,pr-true,q-80/a182-ofzeta/pv/a8/86/c9/b2407a25bf4b073277f181e845.jpg",
      "https://images.tcdn.com.br/img/img_prod/1182338/jaqueta_corta_vento_feminina_04_531_1_59dea3addff1afcb3151513d2de6275d.jpg",
      "https://blacktarg.cdn.magazord.com.br/img/2022/01/produto/996/jaqueta-corta-vento-black-ghost-4.png?ims=fit-in/635x865/filters:fill(white)",
    ],
    preco: 219.9,
    estoque: 18,
    loja: "UrbanStyle",
    descricao: `A Jaqueta Corta-Vento combina leveza e resistência à água, oferecendo proteção em dias frios ou chuvosos, ideal para esportes, caminhadas e uso urbano.`,
    categoria: "Moda",
    tags: ["esporte", "roupa", "inverno"],
  },
  {
    id: 16,
    nome: "Console Gamer PlayOne X",
    images: [
      "https://down-br.img.susercontent.com/file/sg-11134201-7rbn1-lmoc836lf4lh83",
      "https://cdn.awsli.com.br/2500x2500/981/981501/produto/175471244/1-t4wr9f2suj.jpg",
      "https://m.media-amazon.com/images/I/51cJ4dcku8L._UF1000,1000_QL80_.jpg",
      "https://ae01.alicdn.com/kf/Sdf72d522dc084d37a21ee4152a39c2b05.jpg",
      "https://img.joomcdn.net/ed08b28e1167b605c2a07b589410c89921546d28_original.jpeg",
    ],
    preco: 3499.0,
    estoque: 6,
    loja: "GameZone",
    descricao: `O Console Gamer PlayOne X traz gráficos em 4K, jogos exclusivos e desempenho de última geração, garantindo horas de diversão imersiva para jogadores de todos os estilos.`,
    categoria: "Eletrônicos",
    tags: ["jogos", "game", "diversão"],
  },
  {
    id: 17,
    nome: "Kit Panelas Antiaderente 5 peças",
    images: [
      "https://cdn.awsli.com.br/600x450/1250/1250980/produto/203589317/1687-iqtasa.jpg",
      "https://t62533.vteximg.com.br/arquivos/ids/945641-1000-1000/20298061PDM001G.jpg?v=638627823856770000",
      "https://m.media-amazon.com/images/I/910TApB3EPL._UF1000,1000_QL80_.jpg",
      "https://cdn.awsli.com.br/2500x2500/1250/1250980/produto/58278319/f627cba0f2.jpg",
      "https://a-static.mlcdn.com.br/800x560/jogo-conjunto-de-panelas-5-pecas-marcolar-aluminio-antiaderente-cereja-com-bege-tampa-de-vidro-kit-bonito-premium/e-cuisine/11571052894/c117d9ec1dcc5f19551e3049917b6995.jpeg",
    ],
    preco: 399.0,
    estoque: 14,
    loja: "Mundo Eletro",
    descricao: `O Kit de Panelas Antiaderente com 5 peças é durável, fácil de limpar e distribui o calor de forma uniforme, sendo essencial para preparar refeições práticas e saborosas.`,
    categoria: "Eletrodomésticos",
    tags: ["cozinha", "casa", "alimentos"],
  },
  {
    id: 18,
    nome: "Colchão Casal OrthoSleep",
    images: [
      "https://img.olx.com.br/images/27/278509433165955.jpg",
      "https://img.olx.com.br/images/64/642522292309594.jpg",
      "https://img.olx.com.br/images/65/654582311235782.jpg",
      "https://static.santimorumbi.com.br/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/I/M/IMG_6037.jpg",
      "https://a-static.mlcdn.com.br/1500x1500/colchao-casal-orthocrin-molas-splendor-top-138x188x32/orthocrinlojaoficial/81-828-003/1037afd5b2b93463a25057dc17281fd3.jpeg",
    ],
    preco: 1799.0,
    estoque: 5,
    loja: "ComfortHome",
    descricao: `O Colchão Casal OrthoSleep combina molas ensacadas e espuma viscoelástica, oferecendo conforto, firmeza e suporte ortopédico para noites de sono tranquilas.`,
    categoria: "Móveis",
    tags: ["quarto", "conforto", "saúde"],
  },
  {
    id: 19,
    nome: "Patins Inline Street",
    images: [
      "https://goroller.com.br/cdn/shop/files/cougar_street_1_1024x1024.webp?v=1739980022",
      "https://cdn.awsli.com.br/500x500/2184/2184386/produto/166793526/73d4d4e390.jpg",
      "https://cdn.dooca.store/148636/products/uspatzegz3kcw9t9bixhvuflnxws6x8o2m37.jpg?v=1719337607&webp=0",
      "http://acdn-us.mitiendanube.com/stores/052/020/products/ufr-ap-white-cj1-52143482b9ce8dda3e16909061970582-640-0.jpg",
      "https://cdn.awsli.com.br/500x500/2184/2184386/produto/310174541/img_3975-f9ax58pfpn.JPG",
    ],
    preco: 499.9,
    estoque: 12,
    loja: "Fit&Run",
    descricao: `Os Patins Inline Street possuem rolamentos ABEC-7 e bota reforçada, garantindo velocidade, estabilidade e segurança, ideais para lazer ou prática esportiva.`,
    categoria: "Esporte",
    tags: ["lazer", "diversão", "fitness"],
  },
  {
    id: 20,
    nome: "Livro: A Jornada do Herói",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=20",
      "https://api.dicebear.com/9.x/shapes/svg?seed=20a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=20b",
    ],
    preco: 59.9,
    estoque: 50,
    loja: "Livraria Central",
    descricao: `"A Jornada do Herói" é um livro de desenvolvimento pessoal inspirado em narrativas clássicas, ajudando o leitor a refletir sobre autoconhecimento, propósito e superação de desafios.`,
    categoria: "Livros",
    tags: ["leitura", "autoajuda", "literatura"],
  },
  {
    id: 21,
    nome: "Programação em JavaScript",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=21",
      "https://api.dicebear.com/9.x/shapes/svg?seed=21a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=21b",
    ],
    preco: 89.9,
    estoque: 35,
    loja: "BookSpace",
    descricao: `"Programação em JavaScript" é um guia prático que ensina desde os fundamentos até técnicas avançadas da linguagem, ideal para estudantes, profissionais e entusiastas da programação web.`,
    categoria: "Livros",
    tags: ["tecnologia", "programação", "javascript"],
  },
  {
    id: 22,
    nome: "Design de Interfaces",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=22",
      "https://api.dicebear.com/9.x/shapes/svg?seed=22a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=22b",
    ],
    preco: 119.0,
    estoque: 20,
    loja: "Estante Cultural",
    descricao: `"Design de Interfaces" apresenta princípios essenciais de UX e UI, com exemplos práticos e boas práticas para criar experiências digitais funcionais e atraentes.`,
    categoria: "Livros",
    tags: ["design", "ux", "ui"],
  },
  {
    id: 23,
    nome: "Introdução à Inteligência Artificial",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=23",
      "https://api.dicebear.com/9.x/shapes/svg?seed=23a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=23b",
    ],
    preco: 149.9,
    estoque: 15,
    loja: "Livraria Central",
    descricao: `"Introdução à Inteligência Artificial" explora conceitos de IA, aprendizado de máquina e suas aplicações, oferecendo uma visão clara para iniciantes e curiosos da área.`,
    categoria: "Livros",
    tags: ["inteligência artificial", "tecnologia", "machine learning"],
  },
  {
    id: 24,
    nome: "Romance do Vento",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=24",
      "https://api.dicebear.com/9.x/shapes/svg?seed=24a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=24b",
    ],
    preco: 49.9,
    estoque: 60,
    loja: "BookSpace",
    descricao: `"Romance do Vento" é uma obra contemporânea que mistura amor, descobertas e dilemas pessoais, envolvente e sensível, ideal para quem aprecia literatura romântica.`,
    categoria: "Livros",
    tags: ["romance", "ficção", "literatura brasileira"],
  },
  {
    id: 25,
    nome: "A História do Tempo",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=25",
      "https://api.dicebear.com/9.x/shapes/svg?seed=25a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=25b",
    ],
    preco: 79.9,
    estoque: 25,
    loja: "Estante Cultural",
    descricao: `"A História do Tempo", de Stephen Hawking, apresenta os mistérios do universo de forma acessível, abordando buracos negros, big bang e a natureza do tempo em uma leitura essencial.`,
    categoria: "Livros",
    tags: ["ciência", "física", "astronomia"],
  },
  {
    id: 26,
    nome: "Marketing Digital 360°",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=26",
      "https://api.dicebear.com/9.x/shapes/svg?seed=26a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=26b",
    ],
    preco: 99.9,
    estoque: 40,
    loja: "BookSpace",
    descricao: `"Marketing Digital 360°" ensina estratégias práticas para posicionar marcas, conquistar clientes e aumentar resultados no ambiente digital, reunindo teoria e prática em um só volume.`,
    categoria: "Livros",
    tags: ["marketing", "negócios", "digital"],
  },
  {
    id: 27,
    nome: "Cozinha Fácil e Saudável",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=27",
      "https://api.dicebear.com/9.x/shapes/svg?seed=27a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=27b",
    ],
    preco: 69.9,
    estoque: 50,
    loja: "Livraria Central",
    descricao: `"Cozinha Fácil e Saudável" reúne receitas nutritivas e rápidas, mostrando que é possível aliar praticidade com uma alimentação balanceada no dia a dia.`,
    categoria: "Livros",
    tags: ["culinária", "saúde", "receitas"],
  },
  {
    id: 28,
    nome: "Fantasia Épica - O Reino Perdido",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=28",
      "https://api.dicebear.com/9.x/shapes/svg?seed=28a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=28b",
    ],
    preco: 59.9,
    estoque: 45,
    loja: "BookSpace",
    descricao: `"Fantasia Épica - O Reino Perdido" é uma aventura cheia de magia, batalhas e mistérios em um universo fantástico que prende o leitor do início ao fim.`,
    categoria: "Livros",
    tags: ["fantasia", "ficção", "aventura"],
  },
  {
    id: 29,
    nome: "Psicologia das Cores",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=29",
      "https://api.dicebear.com/9.x/shapes/svg?seed=29a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=29b",
    ],
    preco: 89.0,
    estoque: 18,
    loja: "Estante Cultural",
    descricao: `"Psicologia das Cores" analisa como as cores influenciam emoções, decisões e o design, sendo leitura essencial para designers, artistas e comunicadores.`,
    categoria: "Livros",
    tags: ["psicologia", "arte", "design"],
  },
  {
    id: 30,
    nome: "Biografia de Nikola Tesla",
    images: [
      "https://api.dicebear.com/9.x/shapes/svg?seed=30",
      "https://api.dicebear.com/9.x/shapes/svg?seed=30a",
      "https://api.dicebear.com/9.x/shapes/svg?seed=30b",
    ],
    preco: 74.9,
    estoque: 28,
    loja: "Livraria Central",
    descricao: `"Biografia de Nikola Tesla" conta a vida de um dos maiores inventores da história, revelando suas descobertas, desafios e contribuições que mudaram o mundo.`,
    categoria: "Livros",
    tags: ["biografia", "ciência", "história"],
  },
];

/**
 * @typedef {{
 *   id: number,
 *   produtos: {
 *     produto: Produto,
 *     qtd: number
 *   }[],
 *   cliente: {
 *     nome: string,
 *     email: string,
 *   },
 *   status: "entregue" | "enviado" | "cancelado",
 *   data: string,
 *   rastreio?: string,
 * }} Pedido
 * */

/** @type {Pedido[]} */
export const PEDIDOS = [
  {
    id: 1,
    produtos: [{ produto: PRODUTOS[0], qtd: 1 }],
    cliente: {
      nome: "José Alberto",
      email: "jose.alberto@example.com",
    },
    status: "entregue",
    data: "10/02/2024",
  },
  {
    id: 2,
    produtos: [
      { produto: PRODUTOS[1], qtd: 1 },
      { produto: PRODUTOS[0], qtd: 1 },
    ],
    cliente: {
      nome: "Demetrio Gomes",
      email: "demetrio.g@example.com",
    },
    status: "enviado",
    data: "15/08/2025",
  },
  {
    id: 3,
    produtos: [
      { produto: PRODUTOS[3], qtd: 1 },
      { produto: PRODUTOS[4], qtd: 3 },
    ],
    cliente: {
      nome: "José Robert",
      email: "jose.robert@example.com",
    },
    status: "cancelado",
    data: "11/08/2025",
  },
  {
    id: 4,
    produtos: [
      { produto: PRODUTOS[5], qtd: 1 },
      { produto: PRODUTOS[2], qtd: 1 },
    ],
    cliente: {
      nome: "Mariana Souza",
      email: "mariana.souza@example.com",
    },
    status: "enviado",
    data: "20/08/2025",
  },
  {
    id: 5,
    produtos: [{ produto: PRODUTOS[7], qtd: 1 }],
    cliente: {
      nome: "Carlos Eduardo",
      email: "carlos.edu@example.com",
    },
    status: "entregue",
    data: "01/09/2025",
  },
  {
    id: 6,
    produtos: [
      { produto: PRODUTOS[8], qtd: 1 },
      { produto: PRODUTOS[9], qtd: 1 },
      { produto: PRODUTOS[2], qtd: 1 },
    ],
    cliente: {
      nome: "Fernanda Oliveira",
      email: "fernanda.oli@example.com",
    },
    status: "enviado",
    data: "05/09/2025",
  },
  {
    id: 7,
    produtos: [{ produto: PRODUTOS[10], qtd: 1 }],
    cliente: {
      nome: "Ricardo Lima",
      email: "ricardo.lima@example.com",
    },
    status: "cancelado",
    data: "07/09/2025",
  },
  {
    id: 8,
    produtos: [
      { produto: PRODUTOS[12], qtd: 1 },
      { produto: PRODUTOS[13], qtd: 1 },
    ],
    cliente: {
      nome: "Ana Beatriz",
      email: "ana.bea@example.com",
    },
    status: "enviado",
    data: "09/09/2025",
  },
  {
    id: 9,
    produtos: [
      { produto: PRODUTOS[14], qtd: 1 },
      { produto: PRODUTOS[6], qtd: 1 },
    ],
    cliente: {
      nome: "Lucas Martins",
      email: "lucas.martins@example.com",
    },
    status: "enviado",
    data: "12/09/2025",
  },
  {
    id: 10,
    produtos: [
      { produto: PRODUTOS[18], qtd: 1 },
      { produto: PRODUTOS[19], qtd: 1 },
      { produto: PRODUTOS[4], qtd: 1 },
    ],
    cliente: {
      nome: "Patrícia Ramos",
      email: "patricia.ramos@example.com",
    },
    status: "entregue",
    data: "15/09/2025",
  },
];

/** @type {Pedido[]} */
export const PEDIDOS_USUARIO = [
  {
    id: 1,
    produtos: [
      { produto: PRODUTOS[5], qtd: 1 },
      { produto: PRODUTOS[20], qtd: 1 },
    ],
    cliente: {
      nome: "Usuário Fulano",
      email: "usuario.fulano@example.com",
    },
    status: "entregue",
    data: "10/02/2024",
    rastreio: "BR123456789HK",
  },
  {
    id: 2,
    produtos: [
      { produto: PRODUTOS[3], qtd: 1 },
      { produto: PRODUTOS[1], qtd: 1 },
    ],
    cliente: {
      nome: "Usuário Fulano",
      email: "usuario.fulano@example.com",
    },
    status: "enviado",
    data: "15/08/2025",
    rastreio: "PX987654321BR",
  },
  {
    id: 3,
    produtos: [
      { produto: PRODUTOS[0], qtd: 1 },
      { produto: PRODUTOS[2], qtd: 3 },
    ],
    cliente: {
      nome: "Usuário Fulano",
      email: "usuario.fulano@example.com",
    },
    status: "cancelado",
    data: "11/08/2025",
    rastreio: "CN543216789US",
  },
];
